// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/anamnese/MobileStep.tsx": () => import("../components/mockups/anamnese/MobileStep.tsx"),
  "./components/mockups/anamnese/StepWithHelp.tsx": () => import("../components/mockups/anamnese/StepWithHelp.tsx")
};
